version: '3.3'
services:
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=javablog
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - javablog-db:/var/lib/mysql

volumes:
  javablog-db: